# Generated by Django 3.1.5 on 2021-01-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0007_auto_20210108_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
